/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Document Mapping class.  Fields:  - `id` - MongoDB document ObjectID \"_id\" field. Mapped to the PydanticObjectId class  Inherited from:  - Pydantic BaseModel - [UpdateMethods](https://roman-right.github.io/beanie/api/interfaces/#aggregatemethods)
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    town: string;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    lng: number;
    /**
     * 
     * @type {Date}
     * @memberof Location
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Location
     */
    updatedAt?: Date;
}
