/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Document Mapping class.  Fields:  - `id` - MongoDB document ObjectID \"_id\" field. Mapped to the PydanticObjectId class  Inherited from:  - Pydantic BaseModel - [UpdateMethods](https://roman-right.github.io/beanie/api/interfaces/#aggregatemethods)
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    id?: string;

    /**
     * 
     * @type {string}
     * @memberof Item
     */
    user_id?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    category: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Item
     */
    photos: Array<string>;
    /**
     * The description of the item
     * @type {string}
     * @memberof Item
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    location: string;
    /**
     * The daily price must be greater than zero
     * @type {number}
     * @memberof Item
     */
    dailyPrice: number;
    /**
     * The weekly price must be greater than zero
     * @type {number}
     * @memberof Item
     */
    weeklyPrice: number;
    /**
     * The monthly price must be greater than zero
     * @type {number}
     * @memberof Item
     */
    monthlyPrice: number;
    /**
     * The minimum rental period must be greater than zero
     * @type {number}
     * @memberof Item
     */
    miniRentalDays: number;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    itemValue?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Item
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Item
     */
    updatedAt?: Date;
}
